services:

  samba:
    image: dperson/samba
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: >
      -u "${SAMBA_USER};${SAMBA_PASS}"
      -s "media;/media;yes;no"
      -s "downloads;/downloads;yes;no"
    environment:
      - TZ=${TZ}
    # Puertos NO estándar en el host para no chocar con el SMB nativo de macOS
    ports:
      - "1139:139"
      - "1445:445"
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ${STORAGE}/Plex Media Server:/config
      - ${MEDIA}:/data
      - ${STORAGE}/tmp:/transcode

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TR_USERNAME}
      - PASS=${TR_PASSWORD}
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}/movies:/movies          # destino final de pelis para Plex
      - ./scripts/transmission:/scripts  # scripts de hooks

  flexget:
    image: lscr.io/linuxserver/flexget:latest
    container_name: flexget
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FG_WEBUI_PASSWD=${FLEXGET_WEBUI_PASS}
      - OS_USER=${OS_USER}
      - OS_PASS=${OS_PASS}
    ports:
      - "5050:5050"
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/data

networks:
  default:
    driver: bridge
