web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules:
  - tasks: [get-subtitles]
    interval:
      minutes: 30

tasks:
  get-subtitles:
    filesystem:
      path:
        - /data/movies
      regexp: '.*\.(mp4|mkv|avi)$'
      recursive: yes
      retrieve: files
    accept_all: yes
    seen: local
    subliminal:
      languages:
        - spa
        - eng
      providers:
        - opensubtitles
      single: no
      hearing_impaired: no
      authentication:
        opensubtitles:
          username: "{? OS_USER ?}"
          password: "{? OS_PASS ?}"
